SELECT * FROM CUSTOMER;

SELECT * FROM TRANSLATE;
INSERT INTO TRANSLATE VALUES('CUST_TYPE', 'C', '1900-01-01', 'A', 'Consumidor');

INSERT INTO TRANSLATE VALUES('CUST_TYPE', 'M', '1900-01-01', 'A', 'Comercial');
